#!/bin/sh -e

case "$1" in
    purge)
	if which ucf >/dev/null; then
		ucf --purge /etc/cron.d/dehydrated
		ucf --purge /etc/dehydrated/domains.txt
	fi
	rm -f /etc/cron.d/dehydrated /etc/cron.d/dehydrated.ucf-*
	rm -f /var/lib/misc/dehydrated.cron
	rm -f /etc/dehydrated/dehydrated.conf*
	if [ -d /etc/dehydrated ] ; then
		rmdir /etc/dehydrated || true
	fi
	rm -rf /var/lib/dehydrated
    ;;
esac

#DEBHELPER#
