#!/bin/sh -e

case "$1" in
    purge)
	if which ucf >/dev/null; then
		ucf --purge /etc/cron.d/letsencrypt
		ucf --purge /etc/letsencrypt/domains.txt
	fi
	rm -f /etc/cron.d/letsencrypt /etc/cron.d/letsencrypt.ucf-*
	rm -f /var/lib/misc/letsencrypt.cron
	rm -f /etc/letsencrypt/letsencrypt.conf*
	if [ -d /etc/letsencrypt ] ; then
		rmdir /etc/letsencrypt || true
	fi
	rm -rf /var/lib/letsencrypt
    ;;
esac

#DEBHELPER#
