#! /bin/sh

set -e

isDigit() {
	test -n "$1" || return 1
	string="$1"
	while [ "${string#[[:digit:]]}" != "$string" ]; do
		string="${string#[[:digit:]]}"
	done
	[ -z "$string" ] || return 1
}

case "$1" in
    configure)

    	. /usr/share/debconf/confmodule

	. /etc/dehydrated/config.local

	if [ ! -d /etc/dehydrated/ ] ; then
		mkdir /etc/dehydrated
	fi

	tmpfile="$( mktemp -t dehydrated.conf.XXXXXXXXXX )"
	chmod 0644 "$tmpfile"

	cat <<EOF > "$tmpfile"
$(hostname -f)
EOF

	[ ! -r /etc/dehydrated/domains.txt -a -r /etc/letsencrypt/domains.txt ] && cp -a /etc/letsencrypt/domains.txt /etc/dehydrated/
	[ ! -r /etc/dehydrated/private_key.pem -a -r /etc/letsencrypt/private_key.pem ] && cp -a /etc/letsencrypt/private_key.pem /etc/dehydrated/
	[ ! -d /etc/dehydrated/certs -a -d /etc/letsencrypt/certs ] && cp -ar /etc/letsencrypt/certs /etc/dehydrated/
	[ ! -d /etc/dehydrated/accounts -a -d /etc/letsencrypt/accounts ] && cp -ar /etc/letsencrypt/accounts /etc/dehydrated/
	if [ ! -r /etc/dehydrated/ns-update-ssh -a -r /etc/dehydrated/ns-update-ssh.pub ] ; then
		if [ -r /etc/letsencrypt/ns-update-ssh -a -r /etc/letsencrypt/ns-update-ssh.pub ] ; then
			cp -a /etc/letsencrypt/ns-update-ssh /etc/letsencrypt/ns-update-ssh.pub /etc/dehydrated/
		fi
	fi

	[ -r /etc/dehydrated/domains.txt ] || ucf --debconf-ok --three-way "$tmpfile" /etc/dehydrated/domains.txt

	rm -f "$tmpfile"

	# read time from cron.d job, if any
	if [ -f /etc/cron.d/dehydrated ] ; then

		min=$( grep -v '^[[:space:]]*\(\#\|$\)' /etc/cron.d/dehydrated \
			2>/dev/null | {
			read min null
			isDigit "$min" && echo "$min"
			} ) || true

	fi

	# get random time if cron.d snippet doesn't exist or is malformed
	if ! isDigit "$min" ; then
		min=$(( $( od -vAn -N2 -tu4 < /dev/urandom ) % 60 ))
	fi

	tmpfile="$( mktemp -t dehydrated.crond.XXXXXXXXXX )"
	chmod 0644 "$tmpfile"

	cat <<EOF >"$tmpfile"
# cron entry for dehydrated

$min * * * * root if test -x /etc/dehydrated/cron.sh; then /etc/dehydrated/cron.sh; else true; fi
EOF
	ucf --debconf-ok --three-way "$tmpfile" /etc/cron.d/dehydrated
	rm -f "$tmpfile"

	if [ ! -r /etc/dehydrated/ns-update-ssh ] ; then
		rm -f /etc/dehydrated/ns-update-ssh /etc/dehydrated/ns-update-ssh.pub
		true | DISPLAY="" ssh-keygen -f /etc/dehydrated/ns-update-ssh >/dev/null 2>&1
		(echo "New ssh-key for letsencrypt certificates\n\n" ; cat /etc/dehydrated/ns-update-ssh.pub ) \
		| mail -s "letsencrypt ssh-key for $(hostname -f)" "$CONTACT_EMAIL"
	fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
